services:

  blog_app:
    command: make docker-run-production
    container_name: blog_app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - POSTGRES_DB=subpolare
      - POSTGRES_USER=subpolare
      - POSTGRES_PASSWORD=subpolare
      - POSTGRES_HOST=postgres
      - TELEGRAM_TOKEN
      - TELEGRAM_MAIN_CHAT_ID
      - SENTRY_DSN
      - PATREON_CLIENT_ID
      - PATREON_CLIENT_SECRET
      - CLUB_OPENID_CONFIG_SECRET
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    env_file:
      - .env
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8022:8022"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

  postgres:
    image: postgres:15
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: subpolare
      POSTGRES_PASSWORD: subpolare
      POSTGRES_DB: subpolare
    volumes:
      - /home/subpolare/pgdata_subpolare:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54324:5432"
