# Generated by Django 5.1.5 on 2026-10-07 16:32

import django.core.validators
import django.db.models.deletion
import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_alter_post_slug_alter_post_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[map.models.validate_latitude], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[map.models.validate_longitude], verbose_name='Долгота')),
                ('color', models.CharField(default='#333333', max_length=7, validators=[django.core.validators.RegexValidator('\\A#[0-9a-fA-F]{6}\\Z', 'Укажите цвет в формате #RRGGBB.')], verbose_name='Цвет колец')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('preview_mode', models.CharField(choices=[('article', 'Из статьи'), ('custom', 'Своё')], default='article', max_length=7, verbose_name='Превью')),
                ('preview', models.BinaryField(blank=True, default=bytes, verbose_name='Подготовленное превью')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_marker', to='posts.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'точка',
                'verbose_name_plural': 'точки',
                'ordering': ('pk',),
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='map_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='map_longitude_range')],
            },
        ),
    ]
