# Generated by Django 5.1.5 on 2026-10-09 16:52

import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('latitude', models.FloatField(validators=[map.models.validate_latitude], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[map.models.validate_longitude], verbose_name='Долгота')),
                ('note', models.CharField(blank=True, help_text='Показывается вместе с названием при наведении на жёлтую точку.', max_length=500, verbose_name='Краткая заметка')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена')),
            ],
            options={
                'verbose_name': 'жёлтая точка',
                'verbose_name_plural': 'жёлтые точки',
                'ordering': ('name', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='map_place_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='map_place_longitude_range')],
            },
        ),
    ]
