# Generated by Django 5.1.5 on 2026-10-09 17:36

from django.db import migrations, models


def classify_places(apps, schema_editor):
    places = apps.get_model("map", "MapPlace").objects.using(schema_editor.connection.alias)
    places.filter(name__in=["Турция", "ОАЭ", "Индия", "Непал"]).update(kind="country")
    # Remove the previously seeded seas and oceans at the owner's request.
    places.filter(name__in=[
        "Северный Ледовитый океан", "Тихий океан", "Белое море", "Баренцево море",
        "Средиземное море", "Чёрное море", "Азовское море", "Каспийское море",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_seed_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapplace',
            options={'ordering': ('name', 'pk'), 'verbose_name': 'посещённое место', 'verbose_name_plural': 'посещённые места'},
        ),
        migrations.AddField(
            model_name='mapplace',
            name='kind',
            field=models.CharField(choices=[('city', 'Город'), ('country', 'Страна')], default='city', help_text='Город или страна, отмеченные точкой на карте.', max_length=7, verbose_name='Тип места'),
        ),
        migrations.AlterField(
            model_name='mapplace',
            name='note',
            field=models.CharField(blank=True, help_text='Показывается при наведении или нажатии на место.', max_length=500, verbose_name='Краткая заметка'),
        ),
        migrations.RunPython(classify_places, migrations.RunPython.noop),
    ]
