limit_req_zone $binary_remote_addr zone=subpolare_blog_limit:10m rate=3r/s;

server {
    listen 80;
    listen [::]:80;
    server_name subpolare.ru www.subpolare.ru;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    if ($host = www.subpolare.ru) {
        return 301 https://subpolare.ru$request_uri;
    }

    return 301 https://subpolare.ru$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name subpolare.ru;

    ssl_certificate     /etc/letsencrypt/live/subpolare.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/subpolare.ru/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    charset utf-8;
    client_max_body_size 15M;

    location /static/ {
        root /var/www;
        expires max;
        add_header Cache-Control "public";
    }
    location /media/ {
        root /var/www;
        expires max;
        add_header Cache-Control "public";
    }

    location / {
        limit_req zone=subpolare_blog_limit burst=50 nodelay;

        proxy_set_header Host              $http_host;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_buffering off;

        proxy_pass http://blog_app:8022;
    }
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name _;
    ssl_certificate     /etc/letsencrypt/live/subpolare.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/subpolare.ru/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    return 404;
}
